### ISSUE TITLE
vorsatz.getField(Feld0001.ART_DES_ADRESSATEN) fehlerhaft

### ISSUE THREAD

**Issue by schosin** [oboehm/gdv.xport#10]
Betrifft Version 3.0.0. Getestet mit der musterdatei von der GDV-Seite.

Gegeben Vorsatz vorsatz:
`vorsatz.getFeld(Bezeichner.ART_DES_ADRESSATEN)` gibt den erwarteten Wert zurück.
`vorsatz.getFeld(Feld0001.ART_DES_ADRESSATEN)` führt zu folgender Fehlermeldung:
`java.lang.IllegalArgumentException: Feld "ART_DES_ADRESSATEN" nicht in Satzart 0001 vorhanden!`

Grund ist die fehlerhafte Umwandlung des Enums in den Bezeichner für den Lookup (techn. Name ArtAdressaten erwartet, ist aber ARTDESADRESSATEN).

Grüße,
schosins

**Comment by oboehm** [comment]
Danke für den Hinweis und die Analyse. Fehler lässt sich reproduzieren (Testfall: gdv.xport.satz.VorsatzTest#testIssue10).
Wird demnächst behoben...

**Comment by oboehm** [comment]
...fixed -> [Build #302](https://travis-ci.org/oboehm/gdv.xport/builds/363288083)

**Comment by oboehm** [comment]
...3.1.0 released -> [Relase Notes](http://www.aosd.de/gdv.xport/changes-report.html#a3.1.0)
