### ISSUE TITLE
Satz.getFeldInhalt(Bezeichner) erstellt neuen Bezeichner

### ISSUE THREAD

**Issue by schosin** [oboehm/gdv.xport#12]
Betroffene Version: 3.1.0

Mir ist aufgefallen, dass Satz.getFeldInhalt(Bezeichner) nicht den Bezeichner durchreicht, sondern an getFeld(String) delegiert, das über den Bezeichner-Konstruktor einen neuen Bezeichner generiert. Gibt es einen Grund dafür? Scheint mir nicht Sinn und Zweck zu sein, aus dem Namen den techn. abzuleiten, wenn der bereits in der Konstante korrekt gepflegt ist. 
Insbesondere, weil Satz.getFeld(Bezeichner).getInhalt() korrekt funktoniert.

Grüße,
schosins

**Comment by oboehm** [comment]
ups, das ist wohl beim letzten Umbau vergessen worden. Ist inzwischen behoben (Branch develop/3.x)
