### ISSUE TITLE
Gruppierung von Datensätzen mit ausgelassenen Teildatensätzen

### ISSUE THREAD

**Issue by schosin** [oboehm/gdv.xport#13]
Getestet mit develop/3.x, Commit 1deb5b1.

Wenn zwei Datensätze der gleichen Satzart aufeinander folgen, aber ein oder mehrere Teildatensätze ausgelassen wurden (konkretes Beispiel war Satzart 100 zwei mal hintereinander, je Satznummer 3 und 5 ausgelassen), führt dies zu einer falschen Gruppierung der Datensätze.

**Gegeben:**
Satzart 100, Satznummer 1
Satzart 100, Satznummer 2
Satzart 100, Satznummer 4
Satzart 100, Satznummer 1
Satzart 100, Satznummer 2
Satzart 100, Satznummer 4

**Erwartet:**
Zwei Datensätze der Satzart 100, jeweils mit Teildatensätzen 1, 2 und 4.

**Tatsächlich:**
Zwei Datensätze der Satzart 100, einmal mit Teildatensätzen 1, 2, 4, 1 und 2, und einmal mit Teildatensatz 4.
Grund ist, dass beim Erstellen des Satzes auf die SatzXml zurückgegriffen wird und dieser für Satzart 100 fünf Teildatensätze vorsieht und diese unabhängig von der Satznummer eingelesen werden.

In meinem Fork (noch nicht gepusht), habe ich das Problem so gelöst, indem ich in [Datensatz.matchesNextTeildatensatz](https://github.com/oboehm/gdv.xport/blob/f24c0b99c404037e3366b7ac3873f4e18d56296b/lib/src/main/java/gdv/xport/satz/Datensatz.java#L478-L504) nicht nur die ersten 7 Zeichen teste, sondern zusätzlich das letzte Zeichen daraufhin, dass beide (aktuelle und letzte Zeile) eine Ziffer sind und die nächste Zeile eine höhere Ziffer als die vorherige hat.
Ist das so eine korrekte Lösung oder muss sichergestellt werden, dass das letzte Zeichen in der aktuellen Satzart auch wirklich die Rolle der Satznummer hat?

Je nachdem könnte ich morgen oder übermorgen einen PR für einen Fix (inklusive Test) erstellen.

Grüße,
schosins

**Comment by oboehm** [comment]
Hallo schosins,

deine Analyse ist korrekt - es ist tatsächlich so, dass 5 Teildatensätze erwartet werden, die in diesem Fall auch kommen. Nur gehören die 2 unterschiedlichen 100er-Sätzen an - diesen Fall hatte ich bis jetzt noch nicht.

Dein Lösungsvorschlag dazu klingt einleuchtend. Wenn ich jetzt den Standard richtig im Kopf habe, ist das letzte Zeichen immer die Satznummer - braucht also nicht extra überprüft werden. Wichtig ist mir an dieser Stelle nur, das dieser Fall durch Tests abgedeckt wird.

Das Hauptproblem bei der GDV-Spezifikation ist, dass sie verschiedene Interpretationsspielräume offen lässt, die von manchen Firmen unterschiedlich kreativ genutzt werden. Von daher sind die Testfälle fast wichtiger als die Dokumentation.

mfg
oli b.
