### ISSUE TITLE
XML vs. Enum-Definition

### ISSUE THREAD

**Issue by schosin** [oboehm/gdv.xport#18]
Aufgrund deines Commits bzgl. Satzart 250 ist mir aufgefallen, dass es sich eventuell lohnen würde, wenn man bei SatzFactory.getSatz(int) bei fehlendem Mapping der Sparte erst versuchen könnte, den XML-Weg zu gehen, und erst wenn der fehlschlägt auf die SatzX-Lösung mit dem "Unbekannt"-Feld.

Eine andere Alternative wäre vielleicht, dass man Datenpaket und DatenpaketStreamer eine Option setzen könnte, in der man XML priorisieren könnte (Prio SatzXml, Prio SatzXml bei fehlendem Mapping der Sparte, Prio SatzX (wie aktuell)).

Das würde jedenfalls einiges an Arbeit ersparen, außer das Ziel ist es weiterhin, den kompletten GDV-Satz als Enums darzustellen.

**Comment by oboehm** [comment]
Der XML-Weg ist ab 1.0 auch der bevorzugte Weg, weil sie auf der XML-Datei von der GDV beruhen. Die Enums waren die Lösung vor 1.0, haben aber immer noch ihre Daseinsberechtigung, da die XML-Datei nicht ganz einfach zu verstehen und auch nicht frei von Widersprüchen ist.

Ah, jetzt sehe ich erst, worauf du hinaus willst. Das ist mir noch gar nicht aufgefallen, dass bei fehlendem Mapping nur der Constructor aufgerufen wird (historisch bedingt). Du hast recht, da wäre es sinnvoller, wenn sich die SatzFactory dann über XmlService.getSatzart(int) den entsprechenden Satz holen würde. Kannst du gerne abändern, ich bin noch mit Satzart 250 beschäftigt - die hat dummerweise die Satznummer mittendrin, während bei allen anderen Satzarten die Satznummer im letzten Byte steht :-( 

Deinen Pull-Request werde ich nachher mergen - nicht dass es zu Konflikten hinterher kommt.

**Comment by schosin** [comment]
Reicht denn die Satzart aus? Müsste nicht zusätzlich die Sparte mit, um den richtigen Satz zu holen?

Werde mir das morgen anschauen.

**Comment by oboehm** [comment]
Es gibt beides:

- SatzFactory.getDatensatz(int)
- SatzFactory.getDatensatz(int, int)

entspechend XmlService:

- SatzFactory.getSatzart(int)
- SatzFactory.getSatzart(SatzTyp)

Der SatzTyp beinhaltet beides - Satzart + Sparte (und auch noch Wagnisart + Teildatensatznummer - die kamen später für Spezialfälle noch hinzu).

**Comment by schosin** [comment]
Nach einem kleinen Test zuhause ist mir aufgefallen, dass der Umbau auf XML_SERVICE.getSatzart(SatzTyp) - auch nur bei gesetzter Satzart - beim kompletten Test der Library zu mehrern Errors und Failures führt, einige davon einzeln durchgeführt aber durchlaufen (z.B. BezeichnerIT und TeildatensatzTest.testValidateIBAN).

Wird also entweder etwas länger dauern, bis ich damit fertig bin (eventuell erst zum WE) oder ich kann einen fehlerhaften PR stellen; was dir lieber ist.

Grüße,
schosins

**Comment by oboehm** [comment]
Hab' heute morgen gesehen, dass ja bereits der XML_SERVICE verwendet wird, wenn ein nicht registrierter Satz generiert wird (in generateSatz(satzart)). Hatte ich gestern übersehen.

**Comment by schosin** [comment]
Bei der Verwendung hatte ich häufiger nur Intro + Unbekannt + Satznummer in den Feldern. Hauptsächlich für z.B. SatzN mit fehlendem MAPPING für die Sparte.

Auf dem Branch von #20 sind die Felder korrekt befüllt (SatzXml statt SatzX).
