### ISSUE TITLE
Gruppierung von Teildatensätzen

### ISSUE THREAD

**Issue by schosin** [oboehm/gdv.xport#26]
Die Lösung des Problemes in #13 war leider nicht ausreichend. Wie es sich jetzt herausstellt, reicht es nicht, zusätzlich das letzte Zeichen zu vergleichen, da es Sätze gibt, wo das letzte Zeichen Inhalt oder Leerstellen ist.
 
Stattdessen müsste man bei der Prüfung, ob eine Zeile zur vorherigen gehört, die Satznummer abhängig von Sparte, Satzart und eventuell anderen Faktoren berücksichtigen. Wir haben schon eine Implementierung, die aber noch an dem Test bzgl. 0220.030 scheitert (TDS 9 soll an erster Stelle vorkommen können, ist das irgendwo dokumentiert in der offiziellen Doku?).

Der PR kommt, sobald es fertig ist und wir es mit ein paar Datenpaketen getestet haben.

Grüße,
schosins

**Comment by oboehm** [comment]
Willkommen beim GDV-Format ;-) Wenn ich mich noch recht erinnere, war das mit TDS 9 an erster Stelle ein Fall aus der Praxis, der per PR reinkam und durch Test abgesichert wurde. In der Doku steht irgendwo "Falls ein Teildatensatz lediglich Initialwerte enthält, kann auf diesen Teildatensatz komplett verzichtet werden."
Aus der Praxis weiß ich aber auch, dass manche Firmen das GDV-Format sehr kreativ auslegen.
