### ISSUE TITLE
NoClassDefFoundError Problem

### ISSUE THREAD

**Issue by LocutusOfPenguin** [oboehm/gdv.xport#36]
java -jar gdv-xport-lib-4.0.1-uberjar.jar -import irgendeine.gdv -export irgendeine.xml

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/status/StatusLogger

Außer bei "-help" bekomme ich das immer.

Heruntergeladen habe ich das JAR von
https://search.maven.org/search?q=g:com.github.oboehm%20AND%20a:gdv-xport-lib&core=gav

**Comment by oboehm** [comment]
Danke für den Hinweis - da muss ich den Build-Prozess prüfen. Ich melde mich wieder, wenn ich den Fehler gefunden habe...

**Comment by oboehm** [comment]
Fehler gefunden - log4j-Bibliothek musste aktualisiert werden. Das Uberjar funktioniert damit wieder. Allerdings kommt folgende Fehlermeldung beim Start:

> ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...

Dies kann aber ignoriert werden.

4.0.2 wird gerade gebaut und in Maven Central hochgeladen. Kann aber noch ein Weilchen dauern, bis es dort ankommt...

**Comment by LocutusOfPenguin** [comment]
Prima  danke!
