### ISSUE TITLE
Umlaute Problem & XML header defekt

### ISSUE THREAD

**Issue by LocutusOfPenguin** [oboehm/gdv.xport#37]
Ich nochmals :-)

**Problem 1**
In der GDV Datei steht zB "73529 Schwäbisch Gmünd"
daraus macht die Lib im -export "xml"

>Schw&#xfffd;bisch Gm&#xfffd;nd              </feld>

Diese "& # xfffd ;" (ohne Leerzeichen) kommen an vielen Stellen im XML vor (sind aber nicht immer "ü").

**Problem 2**
Auch mag mein Programm den Header nicht.
<?xml version="1.0" encoding="ISO-8859-1"?>
<datenpaket xmlns="http://labs.agentes.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:schemaLocation="http://labs.agentes.de /xsd/datenpaket.xsd">

=> da ist ein Leerzeichen vor "/xsd"

**Comment by oboehm** [comment]
Muss ich erst untersuchen, was hier schiefgelaufen ist (Problem 1). Problem 2 sollte sich erledigen, wenn ich den Header aktualisiere (die URL existert nicht mehr).

**Comment by oboehm** [comment]
Header ist jetzt aktualisiert und Umlaut-Problem ist ebenfalls behoben. Ursache dafür war, dass die GDV-Datei nicht mit ISO-8859-1-Encoding, sondern mit Default-Encoding gelesen wurde (meist UTF-8).
4.0.3 ist gebaut und sollte demnächst in Maven-Central aufschlagen. Viel Spass beim Ausprobieren ;-)

**Comment by LocutusOfPenguin** [comment]
funkt. danke.

**Comment by oboehm** [comment]
Das freut mich.
