### ISSUE TITLE
toString vs. getData on Characters

### ISSUE THREAD

**Issue by MarkusFieber** [oboehm/gdv.xport#4]
I noticed some problems in enterprise environment, when another STAX implementation ("woodstox" together with JBOSS-EAP) leads to a NumberFormatException while parsing your "VUVM2013" and  "fehlendeFelder" XMLs.

The problem is easily fixed in XmlHelper.addAsProperty where `<event.asCharacters().toString>` must be replaced with `<event.asCharacters().getData()>` as the API suggests.

I patched the line in our local repository myself but maybe you can add this fix in 2.1.1?

TIA

**Comment by oboehm** [comment]
bug is fixed now in develop/2.1 branch. I will try to release a 2.1.1 this weekend (after I fixed your other comment with gdv.xport.satz.feld.sparte10.wagnisart48.Feld221Wagnis48#ABSOLUTER_DYNAMIKERHOEHUNGSBETRAG_IN_WAEHRUNGSEINHEITEN

**Comment by oboehm** [comment]
2.1.1 is out.

**Comment by MarkusFieber** [comment]
Thanks a lot!
