### ISSUE TITLE
Instructions unclear for running gdv-xport-service

### ISSUE THREAD

**Issue by janjagusch** [oboehm/gdv.xport#42]
Hi, thanks for building gdv.xport!

While trying to [start the gdv-xport-service](https://github.com/oboehm/gdv.xport/tree/master/service#start), I noticed that the instructions are not 100% clear when it comes to creating the `gdv-xport-service-x.y.z.jar` file.

I assume that the right thing to do it to run `mvn package` from the source root, but I am not familiar with Java - let alone package management in Java - so I might be wrong. Considering that this service aims to provide an interface to different programming languages, maybe it would be useful for people like me to add instructions on how to create the `.jar` file.

What do you think? :smiley:

**Comment by oboehm** [comment]
Good idea.

**Comment by oboehm** [comment]
Documentation how to build gdv.xport is now updated on branch [develop](https://github.com/oboehm/gdv.xport/blob/develop/doc/build.adoc)
