### ISSUE TITLE
gdv-xport-service POST routes have too many arguments

### ISSUE THREAD

**Issue by janjagusch** [oboehm/gdv.xport#45]
Hi!

Looking at the [Swagger UI](https://gdv-xport-400.herokuapp.com/swagger-ui.html#/datenpaket-controller), two routes seem to have too many arguments:

* [/api/v1/Abweichungen](https://gdv-xport-400.herokuapp.com/swagger-ui.html#/datenpaket-controller/validateUsingPOST_1)
* [/api/v1/Datenpaket](https://gdv-xport-400.herokuapp.com/swagger-ui.html#/datenpaket-controller/importDatenpaketUsingPOST)

From what I understand, both of them should accept `text` and the datenpaket route should also accept `format`. However, the also accept two more `body` arguments. I have attached a screenshot for clarity:

![image](https://user-images.githubusercontent.com/25852654/83752932-a9df9300-a669-11ea-969a-19cf5c0fc973.png)

I believe something is wrong in the Swagger specification but am not able to locate it (when we work with OpenAPI, we usually define an [app.yml](https://swagger.io/specification/) file).

Would be awesome, if you could take a look at it! :smiley:

**Comment by oboehm** [comment]
It looks like a misuse of the Swagger annotations in DatenpaketController. I will take a look to it at the weekend.

**Comment by oboehm** [comment]
The swagger documentation is now updated on the dev [develop](https://github.com/oboehm/gdv.xport/tree/develop) branch. Also the Dockerfile and POM was updated to build it via Docker.

**Comment by oboehm** [comment]
v4.1.0 is out where Swagger documentation is fixed - see [release notes](https://github.com/oboehm/gdv.xport/blob/master/CHANGELOG.md)
So this ticket is closed now.
