### ISSUE TITLE
Satzart 221, Sparte 10 "Leben - Berufsunfähigkeit = Wagnisart 4 und 8"

### ISSUE THREAD

**Issue by MarkusFieber** [oboehm/gdv.xport#5]
`gdv.xport.satz.feld.sparte10.wagnisart48.Feld221Wagnis48#ABSOLUTER_DYNAMIKERHOEHUNGSBETRAG_IN_WAEHRUNGSEINHEITEN,`

must be

```java
@FeldInfo(teildatensatz = 1, nr = 11, type = Betrag.class, anzahlBytes = 12, byteAdresse = 62)
ABSOLUTER_DYNAMIKERHOEHUNGSBETRAG_IN_WAEHRUNGSEINHEITEN,
```

the "anzahlBytes" must be changed from 14 to 12
http://www.gdv-online.de/vuvm/bestand/rel2015/ds0221.010.48.1.htm

**Comment by oboehm** [comment]
Fixed in 2.1.1
