### ISSUE TITLE
Offizielles Image auf docker.io / docker hub bereitstellen und via automatischen Build aktuell halten

### ISSUE THREAD

**Issue by k0pernikus** [oboehm/gdv.xport#51]
Die Schritte, das Repository auszuchecken und den Container manuell zu bauen, sind unnötig. Als Nutzer des Tools möchte ich in erster Linie einen Container nutzen, indem ich ihn mir von docker-hub herunterlade.

Ich hab das unter meinen Fork einmal selbst erstellt:

https://hub.docker.com/repository/docker/k0pernikus/gdv.xport

Das kann ich (und andere) frei verwenden via:

    $ docker run --rm  -p 2517:2517 k0pernikus/gdv.xport

Und im Browser ist das Tool dann unter `localhost:2517` erreichbar.

Allerdings müsste ich meinen Fork aktuell halten. Deswegen wäre es ideal wenn ich ihr ein Auto-Build-Image unter eurem Namespace anbietet, bspw. `oboehm/gdv.xport`, welcher dann automatisch bei Github-Changes ein neues Image baut.

**Comment by oboehm** [comment]
Danke für die Anregung - werde ich mich bei Gelegenheit schlau machen, wie ich das auf docker-hub bekomme...

**Comment by oboehm** [comment]
Image wird jetzt über https://hub.docker.com/r/oboehm/gdv.xport bereitgestellt.

**Comment by oboehm** [comment]
Autobuild ist für Docker-Hub ist aktiviert, README wurde angepasst.

**Comment by Klausus01** [comment]
Hallo Philipp,
auch wenn dieser Issue schon eine Weile geschlossen und damit erledigt ist...
Hast du schon die Umfrage zur Notwendigkeit der Bezeichner-Konstanten entdeckt? Oli hat sie vor ein paar Tagen auf die Projektseite gesetzt.
Schau bitte mal rein. Für die kommende GDV-Version 2023 wäre es sehr hilfreich, auf Anpassungen der Konstanten verzichten zu können.
Gruß Klaus
