### ISSUE TITLE
Fehlende Bezeichner

### ISSUE THREAD

**Issue by philoliver** [oboehm/gdv.xport#53]
Hallo Zusammen,

Ich möchte Felder aus `0210.080` mappen. Zum Beispiel `TDS1/23 - Jahr letzte Prämienrückgewähr`. Allerdings gibt es dafür keinen `Bezeichner`. Sind die `Bezeichner` nicht automatisch aus der XML erstellt worden? Wenn nein, was ist die empfohlene Vorgehensweise dennoch an die Felder zu gelangen? (Es fehlen noch weiter Bezeichner aus 0210.080, wenn ich das richtig verstehe).

Vielen Dank!
Beste Grüße,
Phil

**Comment by oboehm** [comment]
Hallo,

die Bezeichner-Konstanten sind alle manuell erstellt worden - war ziemlich mühsam. Und wie du bemerkt hast, fehlen da noch einige. Du kannst die fehlende Bezeichner aber einfach selbst über den Konstruktor oder die of-Methode anlegen:

```javas
Bezeichner b = Bezeichner.of("Praemienrueckgewaehr");
```
Versuch's mal damit. Falls es nicht klappt, melde dich einfach nochmal - es gibt da einige Besonderheiten in der XML-Beschreibung, wo es etwas kniffliger wird und man den Konstruktor verwenden muss.

Und falls es klappt, lass mir die fehlenden Bezeichner zukommen (z.B. als PullRequest auf dem develop-Branch), damit es der nächste einfacher hat...

**Comment by philoliver** [comment]
Hallo,

danke für die Info! Es funktioniert schon sehr gut.

Leider kann ich noch nicht alle Felder testen; ich werde einen Pull request erstellen, wenn ich mir da sicher bin. Ich habe bisher die Bezeichner aus http://www.gdv-online.de/vuvm/bestand/rel2018/ als Parameter an `Bezeichner.of()` übergeben. Sollte ich besser den technischen Bezeichner aus der `.xml` nehmen, um auf Nummer sicher zu gehen?

Viele Grüße!

**Comment by oboehm** [comment]
Das freut mich. Statt des of()-Aufrufs kannst du auch den Konstruktor verwenden (siehe Konstanten in Bezeichner-Klasse):

```
new Bezeichner("Laenderkennzeichen", "LKZ");
```
Normalerweise wird der technische Name aus dem Namen abgeleitet, aber manchmal versagt da der Algorithmus (es gibt da zu viele Ausnahmen).

Im Falle von Laenderkennzeichen müsste aber eigentlich auch

```
Bezeichner.of("Laenderkennzeichen");
```
funktionieren, da es ihn bereits als Konstante gibt. Oder du verwendest einfach die Konstante (`Bezeichner.LAENDERKENNZEICHEN`).
