### ISSUE TITLE
Rechtschreibfehler von dem Wort Formatierung

### ISSUE THREAD

**Issue by andyfined** [oboehm/gdv.xport#57]
Moin,

mir ist aufgefallen dass an mehreren Stellen das Wort Formatierung mit zwei t geschrieben wurde.

**Comment by oboehm** [comment]
Danke für den Hinweis und die Korrektur - ist jetzt gemerge't.

**Comment by Klausus01** [comment]
Hallo Andy,
auch wenn dieser Issue schon eine Weile geschlossen und damit erledigt ist...
Hast du schon die Umfrage zur Notwendigkeit der Bezeichner-Konstanten entdeckt? Oli hat sie vor ein paar Tagen auf die Projektseite gesetzt.
Schau bitte mal rein. Für die kommende GDV-Version 2023 wäre es sehr hilfreich, auf Anpassungen der Konstanten verzichten zu können.
Gruß Klaus
