### ISSUE TITLE
Unterschied zwischen Klasse Bezeichner und VUVM2013.xml

### ISSUE THREAD

**Issue by MarkusFieber** [oboehm/gdv.xport#6]
Hallo zusammen,

ich versuch's heute mal auf Deutsch, das macht es vielleicht einfacher :)

Ich hab mit der neuen Version 2.1.1 weitergearbeitet und konzentriere mich dabei auf die Satzart 200 TDS 1
Nun habe ich festgestellt, dass das Parsen einer entsprechenden Zeile tadellos funktioniert, der Zugriff auf die Daten dann allerdings für bestimmte Daten nicht - weil die im VUVM2013.xml und der Klasse gdv.xport.feld.Bezeichner hinterlegten/erzeugten namen/technischen Bezeichner nicht übereinstimmen.

Das Beispiel, an dem ich drauf stieß ist Feld 22 aus 200.1 "Gesamtbeitrag (Netto) in Währungseinheiten" 

Bei dem ist im XML "Gesamtbeitrag (Netto) in Währungseinheiten/GesbeitragNettoInWE" hinterlegt (Zeile 4970), der Call-Pfad in "Bezeichner" generiert allerdings aus dem "name"-Parameter an den c'tor (Zeile 346) "GesamtbeitragNetto".

Ähnlich verhält sich das wahrscheinlich auch mit dem GesamtbeitragBruttoInWE und mit allen, in denen der Bezeichner-Feldname "_IN_WAEHRUNGSEINHEITEN" enthält, der c'tor-Parameter aber nicht. 

Ändere ich den name-Parameter in Bezeichner#346 auf "Gesamtbeitrag (Netto) in Waehrungseinheiten" kann ich auch auf das Feld und den Wert zugreifen.

Hinweis: Ich verwende auf der Clientseite "gdv.xport.satz.Satz#get(java.lang.Enum<?>)"

Ist das schnell fixbar? 

Sonst baue ich mir wieder eine lokale Variante für unseren Nexus.

**Comment by MarkusFieber** [comment]
Bei weiteren Vergleichen sind mir auch einige "...summer" (statt "...summe") aufgefallen, die potentiell ebenfalls umbenannt werden müssen? In der XML gibt es nur "...summe".

**Comment by MarkusFieber** [comment]
Und, nur aus Neugier, noch die Frage: wieso gibt es überhaupt diese doppelte Datenhaltung XML vs. Fields?

**Comment by oboehm** [comment]
Zur letzten Frage: das ist historisch bedingt. Das XML gab es früher nicht (bzw. war nicht frei verfügbar). Deswegen konnten (und können noch) die Datensätze als Enum beschrieben werden. Davor wurden die Datensätze von Hand codiert.

Zur ursprünglichen Fragestellung: aktuell bin ich auf dem Sprung in den Urlaub. Das einfachste ist es, du clonst das Projekt (hast du vermutlich schon gemacht) und schickst mir dann einen Pull-Request oder die Änderungen zu.

Was auch nicht schlecht wäre, wenn du Test-Datensätze hast, die du mir zuschicken kannst.

**Comment by MarkusFieber** [comment]
Ok, ich schaue mal, was ich, neben der Arbeit, hinbekomme :)
Dir schönen Urlaub und nochmal herzlichen Dank für das Projekt

**Comment by oboehm** [comment]
Hallo Markus,

ich habe jetzt im develop/2.1-Branch alle Bezeichner-Konstanten mit _IN_WAEHRUNGSEINHEITEN und auch die SUMMER-Konstanten angepasst. Momentan bin ich gerade dabei, eine neues Release 2.1.3 vorzubereiten, mit dem ich dieses Ticket hier schließen möchte. Gibt es noch etwas von deiner Seite, das mit ins Release rein müsste oder dass ich mergen müsste?

mfg
oli b.

**Comment by MarkusFieber** [comment]
Hallo Oli,

nein danke, aktuell arbeitet Deine Bibliothek im Rahmen unserer Anforderungen ohne Auffälligkeiten :)
Danke.
Du hattest ja auch Kontakt zu NiasSt90? Das ist ein Kollege von mir und der hatte unsere letzten Änderungen hochgegeben.

Gruß
Markus

**Comment by oboehm** [comment]
Freut mich, dass es so unaffällig funktioniert. Grüß mir NiasSt90 von mir.
2.1.3 ist draußen - daher schließe ich jetzt das Ticket.

mfg
oli b.
