### ISSUE TITLE
Abgespeckte VUVM2018.xml

### ISSUE THREAD

**Issue by oboehm** [oboehm/gdv.xport#60]
Nicht immer werden allen Datensätze aus der GDV-Schnittstellenbeschreibung (aus VUVM2018.xml) benötigt. Daher solllte
* eine abgespeckte VUVM.xml erzeugt werden können; nach Übergabe eine Liste aller gewünschten Satzarten (bzw. SatzTypen), sollten auch nur diese in der VUVM.xml landen
* für die Generierung von GDV-Datensätze sollte alternativ zur VUVM2018.xml die agespeckte Version VUVM.xml als Vorlage angegeben werden können

**Comment by Klausus01** [comment]
Das darf nicht nur für VUVM2018 möglich sein sondern auch für VUVM2013 und VMVM2015. Auch muss in den 'abgespeckten' VUVMXXXX auch das <info>-Tag der Quell-VUVMXXXX enthalten sein.
