### ISSUE TITLE
Datensätze mit Sparte Leben werden nicht korrekt geparst

### ISSUE THREAD

**Issue by markusneidhart** [oboehm/gdv.xport#61]
Guten Tag,

mir ist bei folgender Datenkonstellation ein Problem beim Parsing aufgefallen:

Wenn ein GDV-Datensatz für Sparte Leben mit Wagnisart "1" oder "3" geliefert wird, und dabei aber nur die Teilsätze 1, 2, und 6 (Bezugsrechte) in genau dieser Reihenfolge geliefert werden, so macht das Parsing nicht ganz was es soll:

Der Teildatensatz 6 (Bezugsrechte) landet fälschlicherweise im 3. Teildatensatz und wird dadurch auf falsch geparst, da die Felder dann natürlich nicht mehr übereinstimmen.

Ich denke, das hängt wohl mit der Logik zusammen, wie die Teilsätze identifiziert werden:
- Satz 0220.010.13.1 sieht 3 Teilsätze vor.
- Die ersten beiden Teilsätze funktionieren korrekt.
- Wenn dann die Zeile mit richtigem Teildatensatz 6 geparst werden soll, wird geprüft, ob die ersten 7 Felder identisch sind (ist der Fall), anschliessend wird geprüft, ob die Satznummer höher ist als die letzte (6 > 2), was auch der Fall ist. Dadurch wird Teildatensatz 6 als 3. Teildatensatz genommen, was aber falsch ist.

Ich könnte mir vorstellen, dass dieses oder ein ähnliches Problem auch bei anderen Wagnisarten/Sparten ein Problem darstellen könnte (habe ich aber nicht verifiziert, resp. noch keine Daten dazu gefunden).

Mögliche Lösung:
- Wäre es möglich oder sinnvoll, bei der Prüfung einer Zeile als nächster Teildatensatz nicht nur zu prüfen, ob die Satznummer grösser ist als der letzte gefundene Teilsatz, sondern auch, ob die Nummer denn grösser ist als die Anzahl der erlaubten Teilsätze? Im oberen Beispiel wäre 6 ja sowieso grösser als 3, daher könnte das gar nicht infrage kommen als Teilsatz.
- Alternativ könnte man wohl auch prüfen, ob die Signatur zu einem anderen Satz passt (0200.010.13.6 hat ja per se eine eigene Satzbeschreibung und käme daher ebenfalls nicht infrage als 3. Teilsatz von 0200.010.13.1).

Beste Grüsse,

Markus

**Comment by oboehm** [comment]
Hallo Markus,

danke für die Analyse. Ich werde dann mal versuchen, einen Datensatz zu erzeugen, um das Fehlverhalten beim Import zu reproduzieren (oder hast du mir zufällig einen Test-Datensatz, den du weitergeben kannst?).

Wenn ich dich richtig verstanden habe, müsste der fehlerhaften Import mit folgender Konstellation auftreten:

1. Satz 0220.010.13.1 mit Teildatensatz 1 + 2
2. danach Satz 0220.010.13.6

mfg,
oli b.

**Comment by markusneidhart** [comment]
Hallo Oli,

ich habe Dir einen Testdatensatz aus meinem richtigen Testfall gebaut, mit dem Du das erkennen solltest. Siehe Anlage
[testcase_0220_010_13.txt](https://github.com/oboehm/gdv.xport/files/7036983/testcase_0220_010_13.txt).

Ja, genau, das ist korrekt so, wie Du es beschrieben hast. Grüsse,

Markus

**Comment by oboehm** [comment]
Hallo Markus,
danke für den Testdatensatz. Eine Frage noch - welche Version verwendest du, v4 oder v5 (mit v5 besteht das Problem auch)?

**Comment by markusneidhart** [comment]
Hallo Oli,

ich verwende 5.0.0, da zumindest besteht das Problem (mit v4 hab ichs nicht versucht).

**Comment by oboehm** [comment]
So, jetzt wird zusätzlich noch die Satznummer herangezogen, ob es vielleicht noch weitere Datensätze des gleichen Typs gibt. Leider waren die Änderungen etwas umfangreicher, so dass es jetzt eine v5.1.0 geworden ist, die soeben ins zentrale Maven-Repo hochgeladen wurde.
Ich denke, morgen dürfte diese Version dann allgemein verfügbar sein. Bitte mal ausprobieren, ob's damit funktioniert.

**Comment by markusneidhart** [comment]
Hallo Oli,

danke, ich habs im Projekt gleich mal getestet, und es funktioniert gut so mit Version 5.1.0. Ich erlaube mir, das Issue zu schliessen. Besten Dank für den Fix. Grüsse,

Markus
