### ISSUE TITLE
Datenlieferung mit Erweiterungssatz für Euro-/Währungsfähigkeit abhängig von Sortierung?

### ISSUE THREAD

**Issue by markusneidhart** [oboehm/gdv.xport#62]
Hallo Oli,

mir ist noch etwas aufgefallen bei einer weiteren Datenlieferung, welche ich parsen wollte. Meine Datei (Daten vom Kunden) hat in etwa folgende Struktur:

Adressteil 0100
Allgemeiner Vertragsteil 0200
Leben 0210
Angaben zur versicherten Person 0220.010.0
0220.010.13.1 Teildatensatz 1
0221.010.13.1 Teildatensatz 1
0220.010.13.1 Teildatensatz 2
0220.010.13.1 Teildatensatz 6 Bezugsrechte
usw.

Das Resultat daraus ist, dass nach dem Parsing der 0220.010.13.1-er Datensatz mit dem ersten Teildatensatz vorhanden ist, dann der 0221.010.13.1-er Datensatz, und dann nochmals ein 0200.010.13.1-er Datensatz, der aber nur den Teildatensatz 2 enthält. Wäre die Reihenfolge im File anders (zuerst beide Teildatensätze von 0220.010.13.1, und erst dann 0221.010.13.1), so gäbe es einen Datensatz für 0220.010.13.1 mit zwei Teildatensätzen drin, und einen Datensatz für 0221.010.13.1.

Der springende Punkt ist, dass sich eine Zeile des Erweiterungssatzes für Euro-/Währungsfähigkeit zwischen dem ersten und dem zweiten Teildatensatz von 0220.010.13.1 befindet.
Gemäss den FAQ der Homepage scheint das erlaubt zu sein (http://www.gdv-online.de/vuvm/bestand/faq.html#ieIstDieReihenfolgeMitDenEuroSaetzenWennEsZweiSpartenSaetzeUndZweiEuroSaetzeGibtZBKFZUnfall). Obwohl die Formulierung auch in der Broschüre selbst ("Die Sätze der Satzart 0211 bzw. 0221 sind im Anschluss an die
zugehörigen Sätze 0210 bzw. 0220 zu liefern.") schon nicht ganz eindeutig ist. Man dürfte da wohl schon erwarten, dass zuerst ein kompletter Satz geliefert wird :-)

Ich denke, das betrifft ggf. sämtliche Sparten. Ob das analog auch bei den 0210/0211-er Sätzen so auftauchen kann, wüsste ich jetzt nicht, könnte evtl. aber sein.

Wie siehst Du das, sollte das Verhalten an der Stelle angepasst werden? Gerne kann ich Dir auch wieder eine Test-Datei liefern falls Du möchtest.

**Comment by oboehm** [comment]
Hallo Markus,

der GDV-Datensatz sorgt doch immer wieder für Überraschungen. Von daher bin ich über Test-Dateien immer dankbar.

Zum Problem: das beim Import umzusetzen, dürfte kaum möglich sein. Was ich mir aber vorstellen kann, das im Nachgang zu machen, z.B. als pack()-Methode. Also sowas in der Art

```java
    datenpaket.importFrom(testfile, "IBM850");
    datenpaket.pack();
```

Damit kann der Aufrufer dann entscheiden, ob er die Datensätze so wie im Original will (ohne pack-Aufruf) oder zusammengefasst.

mfg,
oli b.

**Comment by markusneidhart** [comment]
Hi Oli,

das wäre sicher ne Option, das im Nachgang zu machen.

Als Workaround werde ich mal versuchen, die Zeilen im File (bevor überhaupt geparst wird) einfach vorgängig zu sortieren und in die "erwartete" Reihenfolge zu bringen (also gruppiert nach VSNR Zeilen gemäss Satzart aufsteigend zu sortieren, natürlich so, dass Teilsätze nachher nicht eine andere Reihenfolge haben). Dann sollte durch "datenpaket.importFrom()" die Struktur korrekt geladen werden können.

Ich werde aber noch ein Testfile erzeugen, um das Ganze isoliert testen zu können, und das werde ich gerne wieder bereitstellen.

Grüsse,

Markus

**Comment by markusneidhart** [comment]
Hallo Oli,

anbei das Testfile. Grüsse,

Markus

[testcase_0220_mit_0221_versetzt.txt](https://github.com/oboehm/gdv.xport/files/7083505/testcase_0220_mit_0221_versetzt.txt)

**Comment by oboehm** [comment]
Datenpaket#pack-Methode wurde mit 5.2.0 eingeführt.
