### ISSUE TITLE
SatzRegistry: Registrierte Datensätze werden nicht richtig geklont

### ISSUE THREAD

**Issue by markusneidhart** [oboehm/gdv.xport#66]
Hi Oli,

wir haben bei uns den Fall, dass wir eine versichererspezifische Satzart einführen müssen. Das machen wir normal, indem wir für die Satzart ein XML definieren, und dieses mittels eines neuen Satztyps registrieren auf der Satz-Registry (mittels gdv.xport.util.SatzRegistry#register(gdv.xport.satz.Satz, gdv.xport.util.SatzTyp)).

Wir haben aber zwei Probleme:

1. Wenn wir so eine Datei importieren, und anschliessend auf dem Datenpaket noch pack() aufrufen, so gibt es eine Exception, weil die oben registrierte Satzart bei isComplete nicht berücksichtigt wird.
2. Beim Import der Datei wird bei der neuen Satzart direkt der generierte Satz aus dem XML zurückgeliefert, statt eine Kopie (siehe gdv.xport.util.SatzRegistry#getDatensatz(gdv.xport.util.SatzTyp), ohne Kopie, gegenüber gdv.xport.util.SatzRegistry#getSatz(gdv.xport.util.SatzTyp), mit Kopie). Das führt dann dazu, dass nur der letzte Datensatz "überlebt".

Ich mache einen Pull-Request mit Test.

**Comment by markusneidhart** [comment]
Pull #67 bereitgestellt. Bitte um Review und ggf. Merge. Sollte sich mit diesem Fix natürlich eine Fix-Version zeitnah (5.2.1 oder so) zeitnah bauen lassen, sind wir natürlich nicht traurig :-)

**Comment by oboehm** [comment]
Tests sehen gut aus. Denke, dass ich diese Woche noch eine 5.3.0 rausgeben kann....

**Comment by oboehm** [comment]
5.3.0 wurde soeben release't...
