### ISSUE TITLE
Pack-Methode funktioniert noch nicht richtig

### ISSUE THREAD

**Issue by markusneidhart** [oboehm/gdv.xport#79]
Hallo Oli,

mir sind bei der Datenpaket.pack() Methode noch zwei Fehler aufgefallen:

1. Lücken werden durchgereicht und verhindern korrekte "Paketierung"
2. Auf mehr als 2 Datensätze aufgeteilte Teildatensätze werden nicht richtig paketiert.

Zu 1, beispielhaft:
Vertrag "12345"
0220.010.13.1, Tds 1
0221.010.13.1, Tds 1
0220.010.13.1, Tds 2
...
Vertrag "12349"
0220.010.13.1, Tds 1
0221.010.13.1, Tds 1
0220.010.13.1, Tds 2
...

Beim "pack" des ersten Vertrags (0220 zusammengefasst) hinterlässt die Prozedur eine Lücke dort, wo der zweite Tds gelegen hat (keine Tds mehr). Diese Lücke wurde aber fälschlicherweise durch den Tds1 vom nächsten Vertrag (hier 12349) wieder aufgefüllt und die Lücken so immer weiter propagiert. D.h. eigentlich hat nur das Pack beim ersten Vertrag wirklich einen Effekt gezeigt.

Zu 2:
0220.010.13.1, Tds 1
0221.010.13.1, Tds 1
0220.010.13.1, Tds 2
0221.010.13.1, Tds 2
0220.010.13.1, Tds 3

Dieses Muster hätte für 0220 die 3 Tds nicht zusammengefasst, sondern hätte einmal 0220 mit Tds 1 und 2 und einmal 0220 mit Tds 3 hinterlassen.

Ist mir mit real-life Daten aufgefallen. Ich mache Dir einen Pull-Request und passen den bestehenden pack-Test entsprechend an. Ich habe dies auf dem neusten develop-Branch gefixt, wäre es aber möglich, dass Du dies auf 5.4 zurückportierst und ggf. eine 5.4.3 lieferst?

**Comment by oboehm** [comment]
PR ist jetzt gemerge't. Allerdings bin ich gerade auf javaland.eu und komme wohl erst am Wochenende zum releasen. Ob ich einen Rückport auf 5.4.3 schaffe, kann ich nicht versprechen. Was spricht denn gegen einen Update auf 6.1?

**Comment by markusneidhart** [comment]
> PR ist jetzt gemerge't. Allerdings bin ich gerade auf javaland.eu und komme wohl erst am Wochenende zum releasen. Ob ich einen Rückport auf 5.4.3 schaffe, kann ich nicht versprechen. Was spricht denn gegen einen Update auf 6.1?

Hallo Oli,

danke vielmals. Das ist schon ok, eilt nicht. Wegen Update auf 6.1: Ja, das wäre schon auch möglich.

**Comment by oboehm** [comment]
Version 6.1.2 ist jetzt draußen. Daher schließe ich jetzt das Ticket. Sollte der Fix auch auf 5.4 benötigt werden, bitte einen neuen Issue aufmachen.

**Comment by markusneidhart** [comment]
> Version 6.1.2 ist jetzt draußen. Daher schließe ich jetzt das Ticket. Sollte der Fix auch auf 5.4 benötigt werden, bitte einen neuen Issue aufmachen.

Genial, danke. 6.1.2 reicht aus.
