### ISSUE TITLE
Satzarten mit ausgelassenen Satznummern werden falsch dargestellt

### ISSUE THREAD

**Issue by apfelbasti** [oboehm/gdv.xport#8]
Wenn die Satzart 100 nur aus den Satznummern 1, 2 und 4 besteht (weil z.B. Satznummer 3 keinen Inhalt hat), wird bei der Formatierung in das HTML-Format der Inhalt der Satznummer 3 für die Satznummer 4 angezeigt. Dies hat zur Folge, dass IBAN und BIC aus Satznummer 4 als Kommunikation aus Satznummer 3 dargestellt wird.
Bei anderen Satzarten wurde das (noch) nicht getestet.

**Comment by oboehm** [comment]
Der Fall trat bis jetzt noch nicht auf und dafür gibt es leider auch keine Testdaten - die hören alle maximal mit Satznummer 3 auf. Können Sie mir einen Testdatensatz dafür zur Verfügung stellen, damit ich das Problem verifizieren und beheben kann?

Bei den anderen Satzarten besteht das Problem vermutlich ebenso - das ging leider nicht aus der Dokumentation hervor, dass "Lücken" zulässig sind. Falls das Problem auftaucht, bitte neues Ticket aufmachen und Testdaten anhängen. In der Zwischenzeit werde ich mir mit selbstgebastelten Testdaten behelfen und nach einer Lösung suchen.

**Comment by apfelbasti** [comment]
In der Dokumentation des GDV steht geschrieben: "Falls ein Teildatensatz lediglich Initialwerte enthält, kann auf diesen Teildatensatz komplett verzichtet werden." 
Ich hab im Anhang die Beispieldatei des GDV "manipuliert". Beide enthalten den Teilsatz 4 mit einer IBAN und BIC. 
[musterdatei_041222_mit_teilsatz_3.txt](https://github.com/oboehm/gdv.xport/files/1443612/musterdatei_041222_mit_teilsatz_3.txt)
[musterdatei_041222_ohne_teilsatz_3.txt](https://github.com/oboehm/gdv.xport/files/1443613/musterdatei_041222_ohne_teilsatz_3.txt)

**Comment by oboehm** [comment]
Danke - ein ähnliches Beispiel hatte ich mir jetzt auch zusammengebaut. Auf dem develop/2.1-Branch ist der Fehler inzwischen behoben. Werde morgen noch einige Tests machen und dann nächste Woche ein neues Release bauen.
