### ISSUE TITLE
Teildatensaetze werden beim Import unter Umstaenden falsch erkannt

### ISSUE THREAD

**Issue by markusneidhart** [oboehm/gdv.xport#82]
Bei ungünstiger Sortierung werden Teildatensaetze für Sparte Leben (versch. Wagnisarten) falsch geparst werden. Passiert z.B. dann, wenn:
0220.010.2.1
0220.010.48.1
0220.010.2.2
geliefert wird. Grund ist, dass die ersten 7 Felder immer identisch sind (da die Wagnisart später geliefert wird). Durch die alte Logik wurde aber der zweite Tds von Wagnisart 2
faelschlicherweise als zweiter Tds von Wagnisart 4/8 interpretiert.
Ich schlage vor, zusätzlich für die neue Zeile noch zu prüfen, ob es sich um den gleichen Satztyp handelt. Falls nicht, wird mit der neuen Zeile ein neuer Datensatz importiert.

PullRequest hinzugefügt

**Comment by oboehm** [comment]
Pull-Request habe ich überprüft und genehmigt. Sieht gut aus.
Ticket wird mit nächstem Release geschlossen.

**Comment by oboehm** [comment]
Ist jetzt mit [6.2.0](https://github.com/oboehm/gdv.xport/releases/tag/gdv-xport-6.2.0) behoben...
