### ISSUE TITLE
Fehler in XML-Dateien Feld 'KFV-Deckungsart' in Satzart "0220.052"!

### ISSUE THREAD

**Issue by Klausus01** [oboehm/gdv.xport#85]
In der originalen VUVMs des GDV wird das Feld "KFV-Deckungsart" als Feld mit 2 Nachkommastellen ausgewiesen.
Der Fehler befindet sich in der \<feld referenz="BN-2003.02.11.22.50.13.992"\>. Hier wird als Datentyp "Fließkomma" mit 2 Nachkommastellen angegeben anstelle von "Numerisch".  Das hat zur Folge, dass die Satzstruktur um 2 Byte zu lang wird!
Die Satzart "0220.052" ist so nicht verwendbar.

In VUVM2009.xml, VUVM2013.xml, VUVM2015.xml und VUVM2018.xml muss jeweils 
`
		<feld referenz="071-072-KfvDeckungsart-Fliesskomma">
			<name>KFV-Deckungsart</name>
			<bytes>2</bytes>
			<datentyp>Fliesskomma</datentyp>
			<nachkommastellen>2</nachkommastellen>
		</feld>
`

ersetzt werden durch

`
		<feld referenz="071-072-KfvDeckungsart-Numerisch">
			<name>KFV-Deckungsart</name>
			<bytes>2</bytes>
			<datentyp>Numerisch</datentyp>
		</feld>
`

Im Anhang gibt's die korrigierten VUVMs.
Bitte so rasch wie möglich die korrigierten VUVMs übernehmen und eine neue Version bauen.

[Korrektur_xml_wg_KFV-Deckungsart_SA0220_052.zip](https://github.com/oboehm/gdv.xport/files/8995370/Korrektur_xml_wg_KFV-Deckungsart_SA0220_052.zip)

**Comment by oboehm** [comment]
Das Feld "KFV-Deckungsart" ist 2 Bytes lang und damit stimmt auch die Länge der Satzstruktur. Andernfalls würde es beim Aufbau der Satzstruktur auch zu einem Fehler kommen. Lediglich die Anzahl der Nachkommastellen macht hier keinen Sinn und wird korrigiert.

**Comment by oboehm** [comment]
mit 6.2.1 behoben

**Comment by oboehm** [comment]
Hallo Klaus,

ich schau mal, ob ich das diese Woche noch hinbekomme. Ansonsten kannst du den XmlService auch mit deiner eigenen (korrigierten) VUVM-Resource instanziieren.

mfg
oli b.

**Comment by Klausus01** [comment]
Hi Oli,
??? ich bin irritiert…
Das hast du doch schon längst korrigiert mit Version 6.2.1…
Gruß
Klaus

Von: Oliver Boehm ***@***.***>
Gesendet: Dienstag, 11. Oktober 2022 11:16
An: oboehm/gdv.xport ***@***.***>
Cc: Junke, Dr. Klaus-Dieter (ik3-sta) ***@***.***>; Author ***@***.***>
Betreff: Re: [oboehm/gdv.xport] Fehler in XML-Dateien Feld 'KFV-Deckungsart' in Satzart "0220.052"! (Issue #85)

Hallo Klaus,

ich schau mal, ob ich das diese Woche noch hinbekomme. Ansonsten kannst du den XmlService auch mit deiner eigenen (korrigierten) VUVM-Resource instanziieren.

mfg
oli b.

**Comment by Klausus01** [comment]
…stimmt. ☺
Und ich hatte dir deshalb auch die korrigierten VUVMs für den Update geschickt.
Gruß
KLaus

Von: Oliver Boehm ***@***.***>
Gesendet: Montag, 17. Oktober 2022 21:08
An: oboehm/gdv.xport ***@***.***>
Cc: Junke, Dr. Klaus-Dieter (ik3-sta) ***@***.***>; Author ***@***.***>
Betreff: Re: [oboehm/gdv.xport] Fehler in XML-Dateien Feld 'KFV-Deckungsart' in Satzart "0220.052"! (Issue #85)

Hallo Klaus,

na ja, die Fehlermeldung kam von dir und als ich das geschrieben habe, war ich im Stress und hatte keine Zeit, nachzuschauen. Deswegen mein Hinweis mit dem Workaround.

mfg
oli b.
