### ISSUE TITLE
Runtime dependencies: h2 und patterntesting

### ISSUE THREAD

**Issue by knob-creek** [oboehm/gdv.xport#90]
Diese beiden Abhängigkeiten sind problematisch:

- die H2-Abhängigkeit ist von einer alten Version mit Vulnerabilities.  Ist diese Abhängigkeit zur Laufzeit wirklich nötig?
- patterntesting ist eine **Test**-Bibliothek mit entsprechenden Abhängigkeiten (u. a. JUnit), was unangenehme Konsequenzen hat. (Im Spring-Boot-Kontext wird JUnit verwaltet, wenn jetzt eine Laufzeit(!)-Bibliothek ebenfalls JUnit referenziert, bringt das das Build-Tool durcheinander.)  Leider kann man patterntesting nicht einfach ausschließen, weil es tatsächlich Referenzen vom Produktivcode darauf gibt (&rarr; ClassNotFoundError).

Könnten wir eine Version ohne diese Abhängigkeiten bekommen?

**Comment by oboehm** [comment]
Sollte machbar sein. Allerdings bin ich die nächsten 10 Tage ohne Rechner unterwegs. Danach schaue ich es mir an…

**Comment by oboehm** [comment]
Sollte jetzt mit 6.6.0 behoben sein.
